routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('groupclient','GroupclientController');
    Route::resource('client','ClientController');
//    Route::get('trash','ClientController1@trash')->name('trash');
//    Route::get('restore/{client}', 'ClientController@restore')->name('restore');
//    Route::get('delete-permanently/{client}', 'ClientController@deletePermanently')->name('parmenetdelete');
//

    Route::resource('groupsupplier','GroupsupplierController');
    Route::resource('supplier','SupplierController');
    Route::resource('item','ItemController');
    Route::resource('product','ProductController');
    Route::resource('purchase','PurchaseController');
    Route::resource('retire','RetireController');
    Route::resource('invoice','InvoiceController');

});


Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
});

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{

    public function products()
    {
        return $this->belongsToMany('App\Product')->withTimestamps();
    }
    public function suppliers()
    {
        return $this->belongsToMany('App\Supplier')->withTimestamps();
    }
}

app/Http/Controllers/Admin/PurchaseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Purchase;
use App\Supplier;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $purchases= Purchase::latest()->get();
        return view('admin.purchase.index',compact('purchases'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $products = Product::all();
        $suppliers = Supplier::all();
        return view('admin.purchase.create',compact('products','suppliers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $purchase = new Purchase;
        $purchase->date = $request->date;
        $purchase->purchase_quantity = $request->purchase_quantity;
        $purchase->buy_price = $request->buy_price;
        $purchase->sell_price = $request->sell_price;
        $purchase->note = $request->note;
        $purchase->save();

        $purchase->products()->attach($request->products);
        $purchase->suppliers()->attach($request->suppliers);

        Toastr::success('Purchase Successfully Saved :)','Success');
        return redirect(route('admin.purchase.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Purchase $purchase)
    {
        return view('admin.purchase.show',compact('purchase'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $suppliers = Supplier::all();
        $products = Product::all();
        $purchase = Purchase::where('id',$id)->first();
        return view('admin.purchase.edit',compact('purchase','suppliers','products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $purchase = Purchase::find($id);
        $purchase->date = $request->date;
        $purchase->purchase_quantity = $request->purchase_quantity;
        $purchase->buy_price = $request->buy_price;
        $purchase->sell_price = $request->sell_price;
        $purchase->note = $request->note;
        $purchase->save();
        $purchase->products()->sync($request->products);
        $purchase->suppliers()->sync($request->suppliers);
        Toastr::success('Purchase Successfully Updated :)','Success');
        return redirect(route('admin.purchase.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Purchase::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/purchase/create.blade.php
@extends('layouts.backend.app')

@section('title','Purchases Product')

@push('css')
        <!-- Bootstrap Select Css -->
<link href="{{ asset('backend/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <form action="{{ route('admin.purchase.store') }}" method="POST" >
            {{ csrf_field() }}
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Purchases Product
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                <input type="date" id="date" class="form-control" name="date">
                                <label class="form-label">Date</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                <input type="number" id="purchase_quantity" class="form-control" name="purchase_quantity">
                                <label class="form-label">Purchase Quantity </label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="number" id="buy_price" class="form-control" name="buy_price">
                                  <label class="form-label"> Buy Price</label>
                                 </div>
                            </div>
                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="number" id="sell_price" class="form-control" name="sell_price">
                                  <label class="form-label"> Sell Price</label>
                                  </div>
                            </div>
                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="text" id="note" class="form-control" name="note">
                                  <label class="form-label"> Note</label>
                                  </div>
                            </div>


                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-blue">
                            <h2>
                              Supplier And Product
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('suppliers') ? 'focused error' : '' }}">
                                    <label for="supplier">Select Supplier</label>
                                    <select name="suppliers[]" id="supplier" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($suppliers as $supplier)
                                            <option value="{{ $supplier->id }}">{{ $supplier->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('products') ? 'focused error' : '' }}">
                                    <label for="product">Select Product</label>
                                    <select name="products[]" id="product" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($products as $product)
                                            <option value="{{ $product->id }}">{{ $product->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <a  class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.purchase.index') }}">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>

                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
    @endsection

    @push('js')
            <!-- Select Plugin Js -->
    <script src="{{ asset('backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <!-- TinyMCE -->


    @endpush

resources/views/admin/purchase/edit.blade.php
@extends('layouts.backend.app')

@section('title','Purchase')

@push('css')
        <!-- Bootstrap Select Css -->
<link href="{{ asset('backend/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <form action="{{ route('admin.purchase.update',$purchase->id) }}" method="POST" >
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EDIT PURCHASE
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="date" id="date" class="form-control" name="date" value="<?php echo date("Y-m-d");?>">
                                    <label class="form-label">Date</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="purchase_quantity" class="form-control" name="purchase_quantity" value="{{ $purchase->purchase_quantity }}">
                                    <label class="form-label">Purchase Quantity</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="buy_price" class="form-control" name="buy_price" value="{{ $purchase->buy_price }}">
                                    <label class="form-label">Buy Price</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="sell_price" class="form-control" name="sell_price" value="{{ $purchase->sell_price}}">
                                    <label class="form-label">Sell Price</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="note" class="form-control" name="note" value="{{ $purchase->note}}">
                                    <label class="form-label">Note</label>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-blue">
                            <h2>
                                Supplier And Product
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('suppliers') ? 'focused error' : '' }}">
                                    <label for="supplier">Select Supplier</label>
                                    <select name="suppliers[]" id="supplier" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($suppliers as $supplier)
                                            <option
                                                    @foreach($purchase->suppliers as $purchase_supplier)
                                                    {{ $purchase_supplier->id == $supplier->id ? 'selected' : '' }}
                                                    @endforeach
                                                    value="{{ $supplier->id }}">{{ $supplier->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('products') ? 'focused error' : '' }}">
                                    <label for="product">Select Product</label>
                                    <select name="products[]" id="product" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($products as $product)
                                            <option
                                                    @foreach($purchase->products as $product_purchase)
                                                    {{ $product_purchase->id == $product->id ? 'selected' : '' }}
                                                    @endforeach
                                                    value="{{ $product->id }}">{{ $product->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <a  class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.purchase.index') }}">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>

                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
    @endsection

    @push('js')
            <!-- Select Plugin Js -->
    <script src="{{ asset('backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <!-- TinyMCE -->
    <script src="{{ asset('backend/plugins/tinymce/tinymce.js') }}"></script>
    <script>
        $(function () {
            //TinyMCE
            tinymce.init({
                selector: "textarea#tinymce",
                theme: "modern",
                height: 300,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true
            });
            tinymce.suffix = ".min";
            tinyMCE.baseURL = '{{ asset('backend/plugins/tinymce') }}';
        });
    </script>

    @endpush

resources/views/admin/purchase/index.blade.php
@extends('layouts.backend.app')
@section('title','Purchase')

@push('css')
        <!-- JQuery DataTable Css -->
<link href="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <a  class="btn bg-primary waves-effect " href="{{ route('admin.purchase.create') }}">
                <i class="material-icons">add</i>
                <span>Add New Purchase </span>
            </a>
        </div>
        <!-- #END# Basic Examples -->
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                             Purchase Report
                            <span class="badge bg-blue">{{ $purchases->count() }}</span>
                        </h2>

                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>

                                    <th>Date</th>
                                    <th>Supplier</th>
                                    <th>Product  Name</th>
                                    <th>Buy Price</th>
                                    <th>Sell Price</th>
                                    <th>Quantity</th>
                                    <th>Total Buy Price</th>
                                    <th>Note</th>
                                    <th>Action</th>


                                </tr>
                                </thead>
                                <tfoot>
                                <tr>

                                    <th>Date</th>
                                    <th>Supplier</th>
                                    <th>Product  Name</th>
                                    <th>Buy Price</th>
                                    <th>Sell Price</th>
                                    <th>Quantity</th>
                                    <th>Total Buy Price</th>
                                    <th>Note</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                                <tbody>



                                @foreach($purchases as $purchase)
                                    <tr>

                                        <td>{{ Carbon\Carbon::parse($purchase->date)->format('d-m-Y ') }}</td>
                                        <td>
                                            @foreach($purchase->suppliers as $supplier)

                                                {{ $supplier->name }} <br/>
                                            @endforeach
                                        </td>
                                        <td>
                                            @foreach($purchase->products as $product)

                                                {{ $product->name }} <br/>
                                            @endforeach
                                        </td>
                                        <td>{{ $purchase->buy_price }}</td>
                                        <td>{{ $purchase->sell_price}}</td>
                                        <td>{{ $purchase->purchase_quantity}}</td>
                                        <td>{{$purchase->buy_price *$purchase->purchase_quantity}}</td>
                                        <td>{{$purchase->note}}</td>

                                        <td class="text-center">
                                            <a href="{{ route('admin.purchase.show',$purchase->id) }}" class="btn btn-info waves-effect">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                            <a href="{{route('admin.purchase.edit',$purchase->id)}}" class="btn btn-primary waves-effect" >
                                                <i class="material-icons">edit</i>

                                            </a>
                                            <button class="btn btn-danger waves-effect" type="button" onclick="deletepurchase({{ $purchase->id }})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form id="delete-form-{{ $purchase->id }}" action="{{ route('admin.purchase.destroy',$purchase->id) }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- #END# Exportable Table -->
    </div>
    @endsection

    @push('js')
            <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="{{ asset('backend/js/pages/tables/jquery-datatable.js') }}"></script>

    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
    <script type="text/javascript">
        function deletepurchase(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-'+id).submit();
            }else if (
                    // Read more about handling dismissals
            result.dismiss === swal.DismissReason.cancel
            ) {
                swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                )
            }
        })
        }
    </script>
    @endpush

resources/views/admin/purchase/show.blade.php
@extends('layouts.backend.app')

@section('title','purchase')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <a href="{{ route('admin.purchase.index') }}" class="btn btn-danger waves-effect">BACK</a>

        <br>
        <br>
        <div class="row clearfix">
            <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-cyan">
                        <h2>
                            Purchase Details

                        </h2>
                    </div>


                    <div class="body">
                        <b>Supplier Name:-</b>
                        @foreach($purchase->suppliers as $supplier)

                            {{ $supplier->name }} <br/>
                        @endforeach
                        <b>Product Name:-</b>

                            @foreach($purchase->products as $product)

                                {{ $product->name }} <br/>
                            @endforeach
                        <b>Note:-</b>
                        {{ $purchase->note}}</br>

                       <b>Date:-</b>
                        {{ Carbon\Carbon::parse($purchase->date)->format('d-m-Y ') }}<br/>

                        <b>Purchase Quantity:-</b>
                        {{ $purchase->purchase_quantity }}<br/>
                        <b>Buy Price:-</b>
                         {{ $purchase->buy_price}}.00<br/>
                        <b>Sell Price:-</b>
                         {{ $purchase->sell_price}}.00<br/>

                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-cyan">
                        <h2>
                            Total Buy Price
                        </h2>
                    </div>
                    <div class="body">
                        {{$purchase->buy_price *$purchase->purchase_quantity}}.00
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header bg-orange">
                        <h2>
                            Total Sell Price

                        </h2>
                    </div>
                    <div class="body">
                        {{$purchase->sell_price *$purchase->purchase_quantity}}.00
                    </div>
                </div>
            </div>

        </div>
    </div>
    @endsection

    @push('js')
            <!-- Select Plugin Js -->
    <script src="{{ asset('backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <!-- TinyMCE -->
    <script src="{{ asset('backend/plugins/tinymce/tinymce.js') }}"></script>
    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>


    @endpush